services:
  backend:
    image: lok1125/mern-backend:1.0
    container_name: mern-backend-hub
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ptcptlst01:01689868380Cong@cluster0.n6uoeez.mongodb.net/cloud-lab?appName=Cluster0&retryWrites=true&w=majority
    networks:
      - mern-network
    restart: always

  frontend:
    image: lok1125/mern-frontend:2.0
    container_name: mern-frontend-hub
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - mern-network
    restart: always

networks:
  mern-network:
    external: true